### ISSUE TITLE
Update erbloom

### ISSUE THREAD

**Issue by Zabrane** [Vonmo/erbloom#14]
Hi @Elzor 

Would it be possible to update `Erbloom` to the latest Rustler and other libs?
```toml
[dependencies]
bincode = "1.3.3"
rustler = "0.31.1"
bloomfilter = "1.0.13"
siphasher = "1.0.0"
serde = { version = "1.0.200", features = ["derive"] }
```

I tried this change but `rebar3` keeps trying to load old Rustler and always failed to build it.

> macOS + Ubuntu 22.04
> Erlang 26.2.1
> rustc -vV
rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)
binary: rustc
host: x86_64-apple-darwin
release: 1.78.0
LLVM version: 18.1.4

Many thanks

**Comment by Zabrane** [comment]
Changing the TOML config file to this solved my issue:
```toml
bincode = "1.3.3"
rustler = {git = "https://github.com/rusterlium/rustler.git", branch="master"}
bloomfilter = "1.0.13"
siphasher = "1.0.0"
serde = { version = "1.0.200", features = ["derive"] }
```
